'use client';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });
import { useState } from "react";
// export const metadata: Metadata = {
//   title: "Chore Manager",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
"use client";
  const [username, setUsername] = useState("test user");
  return (

    <div lang="en">
      <Header username={username} />
      <body className={inter.className}>{children}</body>
      <Footer />
    </div>
  );
}
